"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type MembershipData = { membership:{ plan:"free" | "plus"; status:string; currentPeriodEnd:string | null }; usage:Record<string,{ used:number; limit:number }>; plans:Record<string,{ name:string; price:number; currency:string; interval:string; features:string[] }>; billing:{ configured:boolean; anonymousAllowed:boolean; checkoutAvailable:boolean } };
const labels: Record<string,string> = { "deep-reading":"AI 深度解读", "follow-up":"连续追问", "affinity-reading":"合缘深读" };

export default function MembershipClient() {
  const [data, setData] = useState<MembershipData | null>(null); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(false);
  useEffect(() => { fetch("/api/membership", { cache:"no-store" }).then((response) => response.json()).then(setData).catch(() => setNotice("会员信息暂时无法读取。")); }, []);
  const checkout = async () => { setLoading(true); setNotice(""); try { const response = await fetch("/api/billing/checkout", { method:"POST", headers:{ "Content-Type":"application/json" }, body:JSON.stringify({ plan:"plus" }) }); const payload = await response.json() as { url?:unknown; error?:unknown }; if (!response.ok || typeof payload.url !== "string") throw new Error(typeof payload.error === "string" ? payload.error : "支付通道暂时不可用。"); window.location.assign(payload.url); } catch (error) { setNotice(error instanceof Error ? error.message : "支付通道暂时不可用。"); } finally { setLoading(false); } };
  const portal = async () => { setLoading(true); try { const response = await fetch("/api/billing/portal", { method:"POST" }); const payload = await response.json() as { url?:unknown; error?:unknown }; if (!response.ok || typeof payload.url !== "string") throw new Error(typeof payload.error === "string" ? payload.error : "暂时无法管理订阅。"); window.location.assign(payload.url); } catch (error) { setNotice(error instanceof Error ? error.message : "暂时无法管理订阅。"); } finally { setLoading(false); } };
  const plus = data?.plans.plus;
  return <main className="membership-shell"><header className="legal-nav membership-nav"><Link href="/" className="legal-brand"><span>✦</span><b>观象</b></Link><nav><Link href="/privacy">隐私政策</Link><Link href="/terms">用户协议</Link><Link href="/">返回首页 ↗</Link></nav></header><section className="membership-hero"><small>MEMBERSHIP · 从免费体验开始</small><h1>让每次观照，<br />都有空间继续深入。</h1><p>基础起卦永久免费；会员只为更高的 AI 解读与连续追问额度付费。</p></section>
    {data && <section className="usage-panel"><div><small>当前方案</small><b>{data.membership.plan === "plus" ? "观象 Plus" : "观象基础"}</b>{data.membership.currentPeriodEnd && <span>本周期至 {new Date(data.membership.currentPeriodEnd).toLocaleDateString("zh-CN")}</span>}</div><div className="usage-bars">{Object.entries(data.usage).map(([feature, item]) => <article key={feature}><span>{labels[feature]}<i>{item.used} / {item.limit}</i></span><div><b style={{ width:`${Math.min(100, item.used / item.limit * 100)}%` }} /></div></article>)}</div></section>}
    <section className="pricing-grid"><article><header><small>FREE</small><h2>观象基础</h2><p><b>¥0</b> / 长期</p></header><ul>{(data?.plans.free.features ?? ["每日 3 次 AI 深度解读","每日 10 次连续追问","每日 2 次合缘深读","本地与匿名云端卦笺"]).map((feature) => <li key={feature}>✓ {feature}</li>)}</ul><Link href="/">继续免费使用 <span>→</span></Link></article><article className="featured"><header><small>PLUS · 推荐</small><h2>观象 Plus</h2><p><b>¥{plus ? plus.price / 100 : 29}</b> / 月</p></header><ul>{(plus?.features ?? ["每日 60 次 AI 深度解读","每日 200 次连续追问","每日 20 次合缘深读","优先模型队列与完整卦笺"]).map((feature) => <li key={feature}>✓ {feature}</li>)}</ul>{data?.membership.plan === "plus" ? <button disabled={loading} onClick={portal}>管理我的订阅 <span>↗</span></button> : <button disabled={loading || !data?.billing.checkoutAvailable} onClick={checkout}>{loading ? "正在连接支付…" : data?.billing.checkoutAvailable ? "开通 Plus" : "支付通道配置中"}<span>→</span></button>}</article></section>
    <section className="billing-note"><b>免费内测说明</b><p>当前版本不会创建订单或发生扣款。Plus 页面用于提前说明未来权益；待账号找回、商户审核、支付回调和退款流程全部验收后才会开放购买。</p>{notice && <em role="status">{notice}</em>}</section><footer className="membership-footer"><span>基础起卦永久免费</span><div><Link href="/privacy">隐私政策</Link><Link href="/terms">用户协议</Link><a href="mailto:2972881811@qq.com">联系客服</a></div></footer></main>;
}
